### ISSUE TITLE
java.lang.ClassCastException: Identified object is not a String.

### ISSUE THREAD

**Issue by GCS-ZHN** [GCS-ZHN/AutoCard#16]
```
(base) PS D:\life_matters\project\java\git_project\public\AutoCard> java -jar target/autocard-1.4.8.jar --app.autoCard.immediate=true
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.9.RELEASE)

[20220511 12:14:29] [main] INFO  top.gcszhn.autocard.App - Starting App v1.4.8 on GCS-ZHN with PID 1652 (D:\life_matters\project\java\git_project\public\AutoCard\target\autocard-1.4.8.jar started by GCS-ZHN in D:\life_matters\project\java\git_project\public\AutoCard)
[20220511 12:14:29] [main] INFO  top.gcszhn.autocard.App - No active profile set, falling back to default profiles: default
[20220511 12:14:29] [main] INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@6200f9cb: startup date [Wed May 11 12:14:29 GMT+08:00 2022]; root of context hierarchy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/D:/life_matters/project/java/git_project/public/AutoCard/target/autocard-1.4.8.jar!/BOOT-INF/lib/spring-core-4.3.13.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[20220511 12:14:29] [main] INFO  org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
[20220511 12:14:29] [main] INFO  org.quartz.simpl.SimpleThreadPool - Job execution threads will use class loader of thread: main
[20220511 12:14:29] [main] INFO  org.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
[20220511 12:14:29] [main] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.3.2 created.
[20220511 12:14:29] [main] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
[20220511 12:14:29] [main] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[20220511 12:14:29] [main] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
[20220511 12:14:29] [main] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.3.2
[20220511 12:14:29] [main] INFO  top.gcszhn.autocard.AppConfig - 用户配置已加载
[20220511 12:14:29] [main] INFO  top.gcszhn.autocard.AppConfig - OCR引擎为D4_OCR
[20220511 12:14:29] [main] INFO  top.gcszhn.autocard.service.MailService - Mail sender is ***
[20220511 12:14:29] [main] INFO  top.gcszhn.autocard.App - 2 user job added
[20220511 12:14:29] [main] ERROR top.gcszhn.autocard.App - Identified object is not a String.
java.lang.ClassCastException: Identified object is not a String.
        at org.quartz.utils.StringKeyDirtyFlagMap.getString(StringKeyDirtyFlagMap.java:378) ~[quartz-2.3.2.jar!/:?]
        at top.gcszhn.autocard.service.AutoCardJob.execute(AutoCardJob.java:56) ~[classes!/:1.4.8]
        at top.gcszhn.autocard.App.lambda$start$0(App.java:77) ~[classes!/:1.4.8]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at top.gcszhn.autocard.App.start(App.java:71) ~[classes!/:1.4.8]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:701) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
        at top.gcszhn.autocard.App.main(App.java:114) ~[classes!/:1.4.8]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[autocard-1.4.8.jar:1.4.8]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[autocard-1.4.8.jar:1.4.8]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) ~[autocard-1.4.8.jar:1.4.8]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) ~[autocard-1.4.8.jar:1.4.8]
AutoCardService stopped
```

**Comment by GCS-ZHN** [comment]
当在`application.json`中配置`maxtrial`时会引发异常·，因为目前maxtrial的参数值要求是字符串，您可以更改为`maxtrial: "5"`而不是`maxtrial: 5`，在接下来的更新中将会解决这个问题。
