### ISSUE TITLE
No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

### ISSUE THREAD

**Issue by Tonny-zhou** [GCS-ZHN/AutoCard#3]
Hello，校友好！
很感谢你写的这个打卡程序，就是我今天用的时候发现提醒邮件发送失败，报错信息如下：
```
[20220205 00:32:56] [DefaultQuartzScheduler_Worker-1] ERROR org.gcszhn.autocard.service.MailService - Could not connect to SMTP host: smtp.zju.edu.cn, port: 994
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
ParentRunner.java:329
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
ParentRunner.java:66
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
ParentRunner.java:293
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
RunBeforeTestClassCallbacks.java:61
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
RunAfterTestClassCallbacks.java:70
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
ParentRunner.java:306
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
ParentRunner.java:413
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
SpringJUnit4ClassRunner.java:190
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:170)
HandshakeContext.java:170
	at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
ClientHandshakeContext.java:103
	at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:222)
TransportContext.java:222
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:449)
SSLSocketImpl.java:449
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:427)
SSLSocketImpl.java:427
	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:549)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:354)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:237)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1927)
SMTPTransport.java:1927
	... 40 more
```
我想问一下这个报错可能是和啥有关呀？是和我服务器设置有关吗？

**Comment by GCS-ZHN** [comment]
邮件已收到，祝您身体健康，工作顺利！

**Comment by GCS-ZHN** [comment]
此前是否发送成功过？可以检查一下服务器与SMTP服务器的网络是否连通。另外可以修改SMTP配置为其他邮件供应商，如QQ邮箱，相关配置可以在对应邮件供应商处获取。



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
发件人: Tonny Zhou ***@***.***&gt;
发送时间: 2022年2月5日 00:48
收件人: GCS-ZHN/AutoCard ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [GCS-ZHN/AutoCard] 发送提醒邮件失败 (Issue #3)





 
Hello，校友好！
 很感谢你写的这个打卡程序，就是我今天用的时候发现提醒邮件发送失败，报错信息如下：
 [20220205 00:32:56] [DefaultQuartzScheduler_Worker-1] ERROR org.gcszhn.autocard.service.MailService - Could not connect to SMTP host: smtp.zju.edu.cn, port: 994
 
我想问一下这个报错可能是和啥有关呀？是和我服务器设置有关吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Tonny-zhou** [comment]
> 

没有发送成功过。我试过把SMTP配置为QQ邮箱的，但是也还是说邮件发送失败。我对linux服务器其实也不是搞得很懂，最后我用笨方法自己写了个py脚本，读取log文件里的信息然后用py的smtplib这个package给我邮箱发，这样是可以发送成功的。

**Comment by GCS-ZHN** [comment]
你可以尝试先用本地window跑一下，如果window可以那应该是你Linux服务器环境原因。你的服务器是个什么环境配置。

**Comment by GCS-ZHN** [comment]
OpenJDK中默认禁用了TLS1.X，需要指定`mail.smtp.ssl.protocols`启用它，而Oracle JDK则默认启用了，无需配置。相关错误已经修复。
